const users = [
  {
    id: 1,
    firstname: 'Ogbonna',
    lastname: 'Basil',
    othername: 'Cea',
    email: 'basilcea@yahoo.co.uk',
    phoneNumber: '08221111111',
    passportUrl: '../../UI/Static/basil.jpg',
    isAdmin: false,
  },
  {
    id: 2,
    firstname: 'Treasure',
    lastname: 'Thsu',
    othername: '',
    email: 'thsu@yahoo.co.uk',
    phoneNumber: '07121111112',
    passportUrl: '../../UI/Static/thsu.jpg',
    isAdmin: false,
  },
  {
    id: 3,
    firstname: 'Enam',
    lastname: 'Chigoz',
    othername: '',
    email: 'chigoz.e@gmail.com',
    phoneNumber: '09021111112',
    passportUrl: '../../UI/Static/chigoz.jpg',
    isAdmin: false,
  },
  {
    id: 4,
    firstname: 'Gbols',
    lastname: 'Oyundele',
    othername: 'Adebisi',
    email: 'oyundele.g@yahoo.co.uk',
    phoneNumber: '09921111112',
    passportUrl: '../../UI/Static/oyundele.jpg',
    isAdmin: false,
  },
  {
    id: 2,
    firstname: 'Mene',
    lastname: 'Bright',
    othername: '',
    email: 'bright.m@gmail.com',
    phoneNumber: '06721111112',
    passportUrl: '../../UI/Static/bright.jpg',
    isAdmin: false,
  },
];

export default users;
